spring:
  application:
    name: lootopia-app
  logging:
    level:
      org.springframework.web: DEBUG
      org.springframework.jdbc.core: DEBUG
      org.springframework.jdbc.datasource: DEBUG
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
KEYCLOAK_REALM: ${KEYCLOAK_REALM}
KEYCLOAK_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

