logging:
  level:
    root: WARN
    com.lootopia: INFO
    org.springframework.security: WARN

spring:
  application:
    name: lootopia-app

  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

server:
  tomcat:
    max-http-form-post-size: 50MB

app:
  jwt:
    issuer: lootopia-app
    access-token-ttl: PT15M
    refresh-token-ttl: P7D
  admin:
    ui:
      enabled: ${ADMIN_UI_ENABLED:false}
  storage:
    upload-dir: ${UPLOAD_DIR:upload}
    rewards-dir: ${UPLOAD_DIR:upload}/rewards
