spring:
  application:
    name: lootopia-app

  logging:
    level:
      org.springframework.jdbc.core: DEBUG
      org.springframework.jdbc.datasource: DEBUG
      .org.springframework.validation=DEBUG:

  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml

  datasource:
    url: jdbc:postgresql://ep-empty-dust-a9kmwkk2-pooler.gwc.azure.neon.tech:5432/lootopia?sslmode=require
    username: lootopia_owner
    password: npg_Qh02jkOzJEHm
    driver-class-name: org.postgresql.Driver
